version: "3.8"

services:
  app:
    build: .
    container_name: vitale-app
    restart: always
    expose:
      - "3000"
    environment:
      PORT: 3000
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - n8n_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vitale.rule=Host(`vitale.h-talks.com.br`)"
      - "traefik.http.routers.vitale.entrypoints=websecure"
      - "traefik.http.routers.vitale.tls.certresolver=leresolver"
      - "traefik.http.services.vitale.loadbalancer.server.port=3000"

networks:
  n8n_network:
    external: true
